import org.gradle.internal.impldep.org.apache.maven.model.Build

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
//    id("custom-plugin")
}

class MyCustomPlugin: Plugin<Project> {
    override fun apply(target: Project) {
        TODO("Not yet implemented")
    }

}

//apply(from = "custom.gradle.kts")

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.websolverpro.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.register("hello") {
    group = "Build"
    description = "custom task description"
    println("Custom task name is $this.name")
    doLast {
        println("do last as :hello")
    }
    // dependsOn("build") // this will create circular reference error
    // as we're also configure the build task to call this task
}

tasks {
    build {
        dependsOn("hello")
    }
}

// can be written with preferred named block
tasks.named<DefaultTask>("build") {
    println("Printing from taskes.named(\"build\")")
    dependsOn("hello")
}

// run ./gradlew hello or ./gradlew :app:hello to run this task
// or attach hello task to build task
println("Hello from :app:build.gradle ")